/*
 * Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.identity.core.dao;

public class SAMLSSOServiceProviderConstants {

    private SAMLSSOServiceProviderConstants() {}

    public static class SqlQueries {

        private SqlQueries() {}

        public static final String ADD_SAML2_SSO_CONFIG = "INSERT INTO IDN_SAML2_SSO_CONFIGS (ISSUER_ID, TENANT_UUID, " +
                "ISSUER, ASSERTION_CONSUMER_URLS, DEFAULT_ASSERTION_CONSUMER_URL, ISSUER_CERT_ALIAS, " +
                "LOGIN_PAGE_URL, NAME_ID_FORMAT, SIGNING_ALGORITHM, DIGEST_ALGORITHM, ASSERTION_ENCRYPTION_ALGORITHM, " +
                "KEY_ENCRYPTION_ALGORITHM, NAME_ID_CLAIM_URI, " +
                "DO_SINGLE_LOGOUT, SLO_RESPONSE_URL, SLO_REQUEST_URL, DO_FRONT_CHANNEL_LOGOUT, " +
                "FRONT_CHANNEL_LOGOUT_BINDING, DO_SIGN_RESPONSE, ASSERTION_QUERY_REQUEST_PROFILE_ENABLED, " +
                "SUPPORTED_ASSERTION_QUERY_REQUEST_TYPES, ENABLE_SAML2_ARTIFACT_BINDING, " +
                "DO_SIGN_ASSERTIONS, ENABLE_ECP, REQUESTED_CLAIMS, ATTRIBUTE_CONSUMING_SERVICE_INDEX, " +
                "REQUESTED_AUDIENCES, REQUESTED_RECIPIENTS, ENABLE_ATTRIBUTES_BY_DEFAULT, IDP_INIT_SSO_ENABLED, " +
                "IDP_INIT_SLO_ENABLED, IDP_INIT_SLO_RETURN_URLS, DO_ENABLE_ENCRYPTED_ASSERTION, " +
                "VALIDATE_SIGNATURE_IN_REQUESTS, VALIDATE_SIGNATURE_IN_ARTIFACT_RESOLVE, ISSUER_QUALIFIER, " +
                "IDP_ENTITY_ID_ALIAS) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, " +
                "?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";


        public static final String UPDATE_SAML2_SSO_CONFIG_BY_ISSUER = "UPDATE IDN_SAML2_SSO_CONFIGS SET " +
                "ISSUER = ?, ASSERTION_CONSUMER_URLS = ?, DEFAULT_ASSERTION_CONSUMER_URL = ?, ISSUER_CERT_ALIAS = ?, " +
                "LOGIN_PAGE_URL = ?, NAME_ID_FORMAT = ?, SIGNING_ALGORITHM = ?, DIGEST_ALGORITHM = ?, " +
                "ASSERTION_ENCRYPTION_ALGORITHM = ?, KEY_ENCRYPTION_ALGORITHM = ?, " +
                "NAME_ID_CLAIM_URI = ?, DO_SINGLE_LOGOUT = ?, SLO_RESPONSE_URL = ?, SLO_REQUEST_URL = ?, " +
                "DO_FRONT_CHANNEL_LOGOUT = ?, FRONT_CHANNEL_LOGOUT_BINDING = ?, DO_SIGN_RESPONSE = ?, " +
                "ASSERTION_QUERY_REQUEST_PROFILE_ENABLED = ?, SUPPORTED_ASSERTION_QUERY_REQUEST_TYPES = ?, " +
                "ENABLE_SAML2_ARTIFACT_BINDING = ?, ENABLE_ECP = ?, DO_SIGN_ASSERTIONS = ?, REQUESTED_CLAIMS = ?, " +
                "ATTRIBUTE_CONSUMING_SERVICE_INDEX = ?, REQUESTED_AUDIENCES = ?, REQUESTED_RECIPIENTS = ?, " +
                "ENABLE_ATTRIBUTES_BY_DEFAULT = ?, IDP_INIT_SSO_ENABLED = ?, IDP_INIT_SLO_ENABLED = ?, " +
                "IDP_INIT_SLO_RETURN_URLS = ?, DO_ENABLE_ENCRYPTED_ASSERTION = ?, VALIDATE_SIGNATURE_IN_REQUESTS = ?, " +
                "VALIDATE_SIGNATURE_IN_ARTIFACT_RESOLVE = ?, ISSUER_QUALIFIER = ?, IDP_ENTITY_ID_ALIAS = ? " +
                "WHERE ISSUER_ID = ? AND TENANT_UUID = ?";

        public static final String DELETE_SAML2_SSO_CONFIG_BY_ISSUER = "DELETE FROM IDN_SAML2_SSO_CONFIGS " +
                "WHERE ISSUER_ID = ? AND TENANT_UUID = ?";

        public static final String GET_SAML2_SSO_CONFIG_BY_ISSUER = "SELECT ISSUER, " +
                "ASSERTION_CONSUMER_URLS, DEFAULT_ASSERTION_CONSUMER_URL, ISSUER_CERT_ALIAS, LOGIN_PAGE_URL, " +
                "NAME_ID_FORMAT, SIGNING_ALGORITHM, DIGEST_ALGORITHM, ASSERTION_ENCRYPTION_ALGORITHM, " +
                "KEY_ENCRYPTION_ALGORITHM, NAME_ID_CLAIM_URI, DO_SINGLE_LOGOUT, " +
                "SLO_RESPONSE_URL, SLO_REQUEST_URL, DO_FRONT_CHANNEL_LOGOUT, FRONT_CHANNEL_LOGOUT_BINDING, " +
                "DO_SIGN_RESPONSE, ASSERTION_QUERY_REQUEST_PROFILE_ENABLED, SUPPORTED_ASSERTION_QUERY_REQUEST_TYPES, " +
                "ENABLE_SAML2_ARTIFACT_BINDING, DO_SIGN_ASSERTIONS, ENABLE_ECP, REQUESTED_CLAIMS, " +
                "ATTRIBUTE_CONSUMING_SERVICE_INDEX, REQUESTED_AUDIENCES, REQUESTED_RECIPIENTS, " +
                "ENABLE_ATTRIBUTES_BY_DEFAULT, IDP_INIT_SSO_ENABLED, IDP_INIT_SLO_ENABLED, IDP_INIT_SLO_RETURN_URLS, " +
                "DO_ENABLE_ENCRYPTED_ASSERTION, VALIDATE_SIGNATURE_IN_REQUESTS, " +
                "VALIDATE_SIGNATURE_IN_ARTIFACT_RESOLVE, ISSUER_QUALIFIER, IDP_ENTITY_ID_ALIAS " +
                "FROM IDN_SAML2_SSO_CONFIGS WHERE ISSUER_ID = ? AND TENANT_UUID = ?";

        public static final String GET_SAML2_SSO_CONFIGS = "SELECT ISSUER, " +
                "ASSERTION_CONSUMER_URLS, DEFAULT_ASSERTION_CONSUMER_URL, ISSUER_CERT_ALIAS, LOGIN_PAGE_URL, " +
                "NAME_ID_FORMAT, SIGNING_ALGORITHM, DIGEST_ALGORITHM, ASSERTION_ENCRYPTION_ALGORITHM, " +
                "KEY_ENCRYPTION_ALGORITHM, NAME_ID_CLAIM_URI, DO_SINGLE_LOGOUT, " +
                "SLO_RESPONSE_URL, SLO_REQUEST_URL, DO_FRONT_CHANNEL_LOGOUT, FRONT_CHANNEL_LOGOUT_BINDING, " +
                "DO_SIGN_RESPONSE, ASSERTION_QUERY_REQUEST_PROFILE_ENABLED, SUPPORTED_ASSERTION_QUERY_REQUEST_TYPES, " +
                "ENABLE_SAML2_ARTIFACT_BINDING, DO_SIGN_ASSERTIONS, ENABLE_ECP, REQUESTED_CLAIMS, " +
                "ATTRIBUTE_CONSUMING_SERVICE_INDEX, REQUESTED_AUDIENCES, REQUESTED_RECIPIENTS, " +
                "ENABLE_ATTRIBUTES_BY_DEFAULT, IDP_INIT_SSO_ENABLED, IDP_INIT_SLO_ENABLED, IDP_INIT_SLO_RETURN_URLS, " +
                "DO_ENABLE_ENCRYPTED_ASSERTION, VALIDATE_SIGNATURE_IN_REQUESTS, " +
                "VALIDATE_SIGNATURE_IN_ARTIFACT_RESOLVE, ISSUER_QUALIFIER, IDP_ENTITY_ID_ALIAS " +
                "FROM IDN_SAML2_SSO_CONFIGS WHERE TENANT_UUID = ?";

        public static final String GET_SAML2_SSO_CONFIG_ID_BY_ISSUER = "SELECT ISSUER_ID FROM IDN_SAML2_SSO_CONFIGS WHERE " +
                "ISSUER_ID = ? AND TENANT_UUID = ?";

    }

}
