# This workflow will sync commits from a PR from master to a target branch.
name: Sync PR from master

on:
  pull_request:
    types:
      - closed
    branches:
      - master

env:
  REPOSITORY: carbon-identity-framework
  GIT_USERNAME: jenkins-is-staging
  PRODUCT_REPOSITORY_FORKED: $GIT_USERNAME'/'${REPOSITORY}
  PRODUCT_REPOSITORY_PUBLIC: wso2/$REPOSITORY
  BUILD_NUMBER: ${{github.run_id}}
  SYNCHRONIZE_BRANCH_NAME: master_sync_github_action/$BUILD_NUMBER
  TARGET_BRANCH_NAME: 6.0.x
  
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "hiii"
          echo ${{ github.event.pull_request }}
